### ISSUE TITLE
make: *** No rule to make target `ins'.  Stop.

### ISSUE THREAD

**Issue by Calips** [matt-42/vpp#7]
$ ./install.sh ins
Cloning into 'iod'...
remote: Counting objects: 1086, done.
remote: Total 1086 (delta 0), reused 0 (delta 0), pack-reused 1086
Receiving objects: 100% (1086/1086), 353.14 KiB | 249.00 KiB/s, done.
Resolving deltas: 100% (737/737), done.
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: E:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: E:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.64.0
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    IOD_INCLUDE_DIR

-- Build files have been written to: C:/MyLibs/CloneByGit/vpp/externals/iod/vpp_build
make: *** No rule to make target `ins'.  Stop.
Cannot install /c/MyLibs/CloneByGit/vpp/externals/iod/vpp_build.

What's the problem ?
PS :  windows 10.

**Comment by rafaguy** [comment]
i have the same issue, anyone can help please?

**Comment by matt-42** [comment]
Indeed, the visual studio c++ compiler still has bugs and can't compile video++. I sent them a bug report one 1-2 years ago but I'm not even sure it was the only problem. I did not spend more time trying to fix the issues. I close this issue, let's try later when the visual studio c++ compiler will have less bugs.

**Comment by rafaguy** [comment]
ok, thank you. i'm beginner with cmake, how to tell cmake to use clang compiler please?

**Comment by matt-42** [comment]
In linux I add -DCMAKE_CXX_COMPILER=clang++ to the command line,
you can also set CMAKE_CXX_COMPILER  to clang++  in cmake-gui.

Matthieu Garrigues
